name: soil_transport_app
description: Soil Transport Management App
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.7.0 <4.0.0" # รองรับ Dart 3.7–3.x
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
    # ให้ตรงกับ Flutter 3.35.x
  # ---- Firebase (ตามชุดที่ใช้อยู่) ----
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_messaging: ^16.0.3
  shared_preferences: ^2.3.2
  # ---- Maps (OpenStreetMap) ----
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  permission_handler: ^11.3.1
  # ---- State & Utils ----
  file_picker: ^10.3.3
  provider: ^6.1.2
  image_picker: ^1.1.2
  # ---- Excel Export ----
  excel: ^3.0.0
  file_saver: ^0.2.13
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true